name: Deploy AWS CDK
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-lastest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Clone the repo
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::123456789100:role/my-github-actions-role
          aws-region: ap-southeast-1

      - name: cdk deploy
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: "deploy"
          working_dir: "cdk"
