name: Deploy AWS CDK
on:
  push:
    branches: [main]
    # paths:
    # - "resize-image-app/**"
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Clone the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Ensure a full clone is performed for accurate path filtering
          path: "resize-image-app" # Clone only the 'resize-image-app' folder
      - name: Debug
        run: |
          ls -l 
          pwd
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::500765386404:role/github.to.aws.oidc
          aws-region: ap-southeast-1

      - name: Navigate to the CDK project directory
        run: cd resize-image-app/cdk

      - name: cdk deploy
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: "deploy"
          cdk_args: "--require-approval never"
